export * from "./github";
export * from "./vercel";

import prisma from "@/lib/prisma";
import { GitHubService, generateProjectFiles } from "./github";
import { VercelService, waitForDeployment } from "./vercel";

// ============================================================================
// UNIFIED DEPLOYMENT ORCHESTRATOR
// ============================================================================

export interface DeploymentConfig {
  projectId: string;
  userId: string;
  componentCode: string;
  componentName: string;
  projectName: string;
  framework: string;
  styling: string;
  deploymentType: "preview" | "production";
  branchName?: string;
}

export interface DeploymentResult {
  success: boolean;
  githubRepoUrl?: string;
  deploymentUrl?: string;
  previewUrl?: string;
  prUrl?: string;
  prNumber?: number;
  commitSha?: string;
  deploymentId?: string;
  error?: string;
}

export async function deployProject(
  config: DeploymentConfig
): Promise<DeploymentResult> {
  // Get user's integrations
  const githubIntegration = await prisma.integration.findUnique({
    where: {
      userId_provider: {
        userId: config.userId,
        provider: "github",
      },
    },
  });

  const vercelToken = process.env.VERCEL_TOKEN;
  const vercelTeamId = process.env.VERCEL_TEAM_ID;

  if (!githubIntegration) {
    return { success: false, error: "GitHub not connected" };
  }

  if (!vercelToken) {
    return { success: false, error: "Vercel not configured" };
  }

  // Get GitHub username
  const githubMetadata = githubIntegration.metadata as any;
  const githubUsername = githubMetadata?.login || githubMetadata?.username;

  if (!githubUsername) {
    return { success: false, error: "GitHub username not found" };
  }

  const github = new GitHubService(githubIntegration.accessToken, githubUsername);
  const vercel = new VercelService(vercelToken, vercelTeamId);

  const repoName = config.projectName
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-");

  try {
    // Step 1: Create or get GitHub repository
    let repoUrl: string;
    const repoExists = await github.repositoryExists(repoName);

    if (!repoExists) {
      const repo = await github.createRepository(
        repoName,
        `Generated by Figgo Pro from Figma design`,
        false
      );
      repoUrl = repo.repoUrl;

      // Initial commit with all project files
      const files = generateProjectFiles(
        config.projectName,
        config.componentCode,
        config.componentName,
        { framework: config.framework, styling: config.styling }
      );

      // Need to initialize repo with a file first
      await github.createOrUpdateFile(
        repoName,
        "README.md",
        files.find((f) => f.path === "README.md")!.content,
        "Initial commit - Figgo Pro"
      );

      // Commit remaining files
      const otherFiles = files.filter((f) => f.path !== "README.md");
      if (otherFiles.length > 0) {
        await github.commitMultipleFiles(
          repoName,
          otherFiles,
          "Add project files - Figgo Pro"
        );
      }
    } else {
      repoUrl = `https://github.com/${githubUsername}/${repoName}`;
    }

    // Step 2: Handle preview vs production deployment
    let commitSha: string | undefined;
    let prUrl: string | undefined;
    let prNumber: number | undefined;

    if (config.deploymentType === "preview" && config.branchName) {
      // Create a branch for preview
      const branchExists = await github.branchExists(repoName, config.branchName);

      if (!branchExists) {
        await github.createBranch(repoName, config.branchName);
      }

      // Update component file on the branch
      const componentPath = `components/${config.componentName}.tsx`;
      const existingSha = await github.getFileSha(repoName, componentPath, config.branchName);

      await github.createOrUpdateFile(
        repoName,
        componentPath,
        config.componentCode,
        `Update ${config.componentName} - Figgo Pro sync`,
        config.branchName,
        existingSha || undefined
      );

      // Create PR
      const pr = await github.createPullRequest(
        repoName,
        `[Figgo Pro] Update ${config.componentName}`,
        `## Design Sync Update

This PR was automatically created by Figgo Pro to sync design changes.

### Changes
- Updated \`${config.componentName}\` component with latest design tokens

### Preview
A preview deployment will be created automatically.

---
*Generated by [Figgo Pro](https://figgo.pro)*`,
        config.branchName,
        "main"
      );

      prUrl = pr.prUrl;
      prNumber = pr.prNumber;
    }

    // Step 3: Create Vercel project and deployment
    let vercelProjectId: string;
    try {
      const vercelProject = await vercel.createProject(repoName, {
        type: "github",
        repo: `${githubUsername}/${repoName}`,
      });
      vercelProjectId = vercelProject.projectId;
    } catch (error: any) {
      // Project might already exist
      if (error.response?.status === 409) {
        const existingProject = await vercel.getProject(repoName);
        vercelProjectId = existingProject.id;
      } else {
        throw error;
      }
    }

    // Step 4: Trigger deployment
    const deployment = await vercel.createDeployment(
      vercelProjectId,
      config.deploymentType
    );

    // Step 5: Wait for deployment to complete
    const deploymentResult = await waitForDeployment(vercel, deployment.deploymentId);

    // Step 6: Record deployment in database
    await prisma.deployment.create({
      data: {
        projectId: config.projectId,
        type: config.deploymentType,
        environment: config.deploymentType,
        triggerType: "manual",
        triggeredBy: config.userId,
        commitSha,
        branch: config.branchName || "main",
        prNumber,
        prUrl,
        status: deploymentResult.success ? "deployed" : "failed",
        deploymentUrl: deploymentResult.url,
        previewUrl: config.deploymentType === "preview" ? deploymentResult.url : undefined,
        platformId: deployment.deploymentId,
      },
    });

    // Update project with deployment info
    await prisma.project.update({
      where: { id: config.projectId },
      data: {
        githubRepoUrl: repoUrl,
        deploymentUrl: deploymentResult.url,
        vercelProjectId,
        status: deploymentResult.success ? "deployed" : "failed",
      },
    });

    return {
      success: deploymentResult.success,
      githubRepoUrl: repoUrl,
      deploymentUrl: deploymentResult.url,
      previewUrl: config.deploymentType === "preview" ? deploymentResult.url : undefined,
      prUrl,
      prNumber,
      commitSha,
      deploymentId: deployment.deploymentId,
      error: deploymentResult.error,
    };
  } catch (error: any) {
    console.error("Deployment failed:", error);
    return {
      success: false,
      error: error.message || "Deployment failed",
    };
  }
}

// ============================================================================
// ROLLBACK DEPLOYMENT
// ============================================================================

export async function rollbackDeployment(
  deploymentId: string,
  userId: string
): Promise<{ success: boolean; error?: string }> {
  const deployment = await prisma.deployment.findUnique({
    where: { id: deploymentId },
    include: { project: true },
  });

  if (!deployment) {
    return { success: false, error: "Deployment not found" };
  }

  if (deployment.project.userId !== userId) {
    return { success: false, error: "Unauthorized" };
  }

  const vercelToken = process.env.VERCEL_TOKEN;
  const vercelTeamId = process.env.VERCEL_TEAM_ID;

  if (!vercelToken || !deployment.project.vercelProjectId) {
    return { success: false, error: "Vercel not configured" };
  }

  try {
    const vercel = new VercelService(vercelToken, vercelTeamId);

    // Get previous successful production deployment
    const deployments = await vercel.listDeployments(
      deployment.project.vercelProjectId,
      20
    );

    const previousProduction = deployments.find(
      (d) => d.target === "production" && d.state === "READY" && d.id !== deployment.platformId
    );

    if (!previousProduction) {
      return { success: false, error: "No previous deployment to rollback to" };
    }

    // Promote the previous deployment
    await vercel.promoteDeployment(
      previousProduction.id,
      deployment.project.vercelProjectId
    );

    // Update database
    await prisma.deployment.update({
      where: { id: deploymentId },
      data: {
        status: "rolled_back",
        rolledBackAt: new Date(),
        rolledBackBy: userId,
      },
    });

    return { success: true };
  } catch (error: any) {
    return { success: false, error: error.message };
  }
}
